### ISSUE TITLE
invalid byte sequence on unicode urls in img src

### ISSUE THREAD

**Issue by jensp** [Toubib/check-webpage#26]
First of all thanks for writing this great plugin, we use it to monitor a lot of blogs at the university I work at. However it has been barfing on sites that link to an image containing non-ascii symbols:

```
/usr/lib/ruby/1.9.1/uri/common.rb:125:in `===': invalid byte sequence in US-ASCII (ArgumentError)
        from /usr/lib/ruby/1.9.1/uri/common.rb:125:in `split'
        from /usr/lib/ruby/1.9.1/uri/common.rb:211:in `parse'
        from /usr/lib/ruby/1.9.1/uri/common.rb:747:in `parse'
        from ./check_webpage.rb:457:in `block in getInnerLinks'
        from ./check_webpage.rb:439:in `times'
        from ./check_webpage.rb:439:in `getInnerLinks'
        from ./check_webpage.rb:606:in `<main>'
```

This is caused by having img tags such as these: `<img src="http://somewhere/testlößnk.jpg" />`
I tried to fix this myself, but my ruby-foo isn't strong enough. I confirmed this against 3c1369f372fa1ddf3d1767ee80f0b44529e22a82 as well as a version from January 2015. I've attached a sample .html file for easy reproduction. [test.html](https://github.com/Toubib/check-webpage/files/98915/test.html.txt)

**Comment by Toubib** [comment]
Yes I saw it too few days ago on one on my websites. I will work on this bug soon, thanks for the report.

**Comment by Toubib** [comment]
Can you test the [issue26-encoding](https://github.com/Toubib/check-webpage/tree/issue26-encoding) branch ?

And you really should update your ruby version, using [rbenv](https://github.com/rbenv/rbenv) if your system has old packages.

**Comment by jensp** [comment]
Thanks for fixing this, it works great with the issue26-encoding branch. 

And yeah, I usually run 2.1, I only tested on 1.9 to ensure it wasn't specific to the ruby version.

Thanks a lot!

**Comment by Toubib** [comment]
Branch merged to master.
